### PR TITLE
Conditionals

### PR DESCRIPTION
**Pull request by MrMeshak**
Hey Robbie 
Could you review this :) 
Thanks

### CODE REVIEW

**Review by encodexed — CHANGES_REQUESTED** [review]
Small typo on line 5, but otherwise great. Fix that first?

**Review by encodexed — APPROVED** [review]
Looks good!

**Comment by encodexed** [comment]
Heh, thought I'd try out the 'request changes' but it got overwritten I think? But yes, days of the week has a typo on line 5 which I'll just let you fix on the main branch afterwards.

**Comment by MrMeshak** [comment]
Thanks Robbie

**Pull request merged**
